apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mhgv3dr7x-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mhgv3dr7x-dotnet-basic-gitops